name: extremedetection
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - sphinx=5.3.0
  - sphinx_rtd_theme=0.4.3
  - sphinx-autobuild 
  - pytest=7.2.0
  - pandas=1.5.2
  - numpy=1.24.1
  - myst-parser=0.18.1
  - scipy=1.10.0
  - netcdf4=1.6.2
  - pip=22.3.1
